### ISSUE TITLE
🐛 [Bug Report] - Thrall will attack a player who mind controls a mob he is fighting in OHF

### ISSUE THREAD

**Issue by DramatimeWoW** [DramatimeWoW/TBC5ManTracker#1]
# Decription: #

If you mind control a mob thrall is attacking in OHF, thrall will stick to the priest that mind controlled the mob after it's dead until the priest Hearthstones and needs to be summoned back to reset thrall

# How it works: #

If you mind control a mob thrall is attacking in OHF, thrall will stick to the priest that mind controlled the mob after it's dead until the priest Hearthstones and needs to be summoned back to reset thrall

# How it should work: #

It should not attack the player who used mind control.

# Source - You need to provide a source as evidence: #

This is common knowledge

# Additional Information: #

**Comment by BlessedPinkie** [comment]
Mind Control disabled in raids atm due to a lack of creature scripted spell cds. Therefore this bug is not present anymore but may reappear later when Mind Control is reenabled.
