### ISSUE TITLE
🐛 [Bug Report] - Unable to speak while in BG

### ISSUE THREAD

**Issue by blade7606** [DramatimeWoW/TBC5ManTracker#17]
# Decription: 
 Unable to speak while in BG

# How it works:  
When playing as the opposite faction (happens to me when I am undead, I play gnome normally) it is impossible to speak in any channel.

# How it should work:  
Should be able to speak while playing as the opposite faction in BG

# Source - You need to provide a source as evidence: #
![image](https://user-images.githubusercontent.com/38160071/62977027-ed6fc480-bdeb-11e9-8210-b4f6e8ecdb17.png)

# Additional Information: #

**Comment by BlessedPinkie** [comment]
Requires a relog during the bg to resolve the issue, you only neeed to do it once. Also duplicate https://github.com/TBC5ManTracker/Issues/issues/15
