### ISSUE TITLE
🐛 [Bug Report] - All interrupts can interrupt delayed

### ISSUE THREAD

**Issue by Atiyo1** [DramatimeWoW/TBC5ManTracker#21]
# Decription: # 
There is a small time window after a cast has finished in which you can still interrupt someone for the full 8-10 seconds, as if you had actually interrupted them.

This seems to work on all interrupts (tested only rogue/both warrior interrupts and mage counterspell)

# How it works: # Caster A casts a spell, the spell hits caster B. Caster B used counterspell right after the spell of caster A was finished. Caster A is now fully kicked on that school, even though the cast was completed.

# How it should work: # Caster A cast a spell, the spell hits Caster B. Caster B used counterspell right after the spell of Caster A was finished. Caster A is not kicked on the school of his cast. He should only receive a 4 sec silence, if caster B is specced into that.

# Source - You need to provide a source as evidence: # https://www.youtube.com/watch?v=tZW_vVauNsg

# Additional Information: #
Although the time window isnt huge, this actually happens a lot especially in bg's. Using r1 frostbolts as a mage is very common, so people don't have the reaction time to interrupt it in time, but rather interrupt slightly too late and you still get a full spelllock on that school.

**Comment by BlessedPinkie** [comment]
I imagine its partly connection delay, not to say there shouldnt be some form of check in the scripts for this particular instance. Thanks for reporting.
