### ISSUE TITLE
🐛 [Bug Report] - Rogue Shadowstep

### ISSUE THREAD

**Issue by Atiyo1** [DramatimeWoW/TBC5ManTracker#26]
# Decription: #
Shadowstep puts you in front of the target
# How it works: #
See above
# How it should work: #
Shadowstep puts you behind the target
# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by oldspices** [comment]
im having it put me out of melee range sadly -- tested on dummy to verify- could be a hitbox thing- looks like gnomes get a free advantage? XD
