### ISSUE TITLE
[Bug Report] - Sethekk Halls Heroic - Darkweaver Syth

### ISSUE THREAD

**Issue by SerpentXSF** [DramatimeWoW/TBC5ManTracker#27]
The first boss Darkweaver Syth spawns adds as his health goes down, however on Heroic difficulty during a run 8/16/2019 at 10 pm EST, the boss keeps spawning adds while not engaged. The Adds also would not despawn after waiting for more than 10 minutes. Some of the Adds were also not elemental, which are what he spawns, they were adds that look similar to the first boss in Blackwing Lair. Please Advise.

Thank you,

**Comment by BlessedPinkie** [comment]
A fix for this was pushed out this morning.
