### ISSUE TITLE
Feral Charge has diminishing returns🐛 [Bug Report] - 

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#28]
# Decription: #
Feral charge has diminishing returns 
# How it works: #
sometimes feral charge is "immune"
# How it should work: #
it never becomes DR as its a immobilize effect like improved hamstring, etc. 
# Source - You need to provide a source as evidence: #
 http://www.youtube.com/watch?v=hS82JzE6F0I&feature=player_detailpage#t=351s
What happends is that at
05:55 the rogue gets rooted by Nature's Grasp and now has controlled root DR for 15 seconds. at
06:00 the druid feral charges and applies Feral Charge immobilize debuff, at
06:04 the debuff fades. Which means even though the rogue still had Controlled Root Dr for 10 more seconds when the immobilize was applied the immobilize was still full duration. Clearly they are on different DRs.
# Additional Information: #
Sucks in PVE AND PVP, And on a side note feral charge also gets resisted way more than usual.

**Comment by BlessedPinkie** [comment]
Theres a wiki document somewhere that lists all the spells that share dr. I'll see if I can find it but that document or something similar would be much better than 1 video that shows a person doing 1 charge.

**Comment by BlessedPinkie** [comment]
A per this list https://wowwiki.fandom.com/wiki/Diminishing_returns and from testing, I can confirm that this is a bug. Now fixed.
