### ISSUE TITLE
🐛 [Bug Report] - Grounding totem does not work in arena (maybe los issue?)

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#30]
# Decription: #
grounding totem is not eating spells. the buff/totem stays up
# How it works: #
grounding totem is not eating spells. the buff/totem stays up
# How it should work: #
even if you are behind a pillar, the grounding totem should eat spells provided it is in range
# Source - You need to provide a source as evidence: #
just watch ANY shaman arena pvp video from tbc you will see clear evidence
# Additional Information: #
cannot possibly pvp in arena until this is fixed

**Comment by oldspices** [comment]
im currently searching for videos (is that best?) I have found forum posts hinting as proof but yea gotta dig through old videos i guess as other private servers dont count??

**Comment by oldspices** [comment]
its quite hard to find content explicitly proving this but i found a old Tbc arena guide which i quote 
"Totems have several interesting properties which are of note.  First, 
they cannot be AOE d, so dont think about killing them with one arcane explosion.
Second, the beneficial totems ignore LOS ... if you're in range, you get the 
buff. " 
Beginner's Guide to World of Warcraft Arena PVP
By doinker08 : David Ishikawa
Version 1.0 - July 14, 2008
Current Patch 2.42 - Arena Season 4
https://gamefaqs.gamespot.com/pc/928901-world-of-warcraft-the-burning-crusade/faqs/53491

i also notice you dont get mana from mana tide when you arent in direct LOS which is not how it should be either. but i see mana spring works los.

**Comment by BlessedPinkie** [comment]
> beneficial totems ignore LOS ... if you're in range, you get the buff.

 I don't think this is referring to grounding totem though.

**Comment by oldspices** [comment]
i will continue to scour for proof, stay tuned.

**Comment by oldspices** [comment]
grounding totem also blocks polymorph but does not get consumed
