### ISSUE TITLE
🐛 [Bug Report] - Teleport when exiting zeppelin

### ISSUE THREAD

**Issue by Siarkowy** [DramatimeWoW/TBC5ManTracker#31]
# Decription: #

Jumping off zeppelin teleports you back to starting location.

# How it works: #

1. Go to Undercity.
2. Take zeppelin to Grom'gol.
3. Wait for Eastern Kingdoms map to load.
4. Jump off zeppelin either (a) immediately or (b) while at destination in Grom'gol.
5. Observe teleport back to Undercity.

# How it should work: #

4. Jump off zeppelin successfully in both cases, without teleporting back to Undercity.

# Source - You need to provide a source as evidence: #

N/A

# Additional Information: #

Seems like a quirk in some anti-cheat logic.

**Comment by BlessedPinkie** [comment]
Ye this is the anti-cheat, I swear I fixed this in a recent update. When did you experience the issue?

**Comment by BlessedPinkie** [comment]
@Siarkowy
