### ISSUE TITLE
🐛 [Bug Report] - Chain lightning breaks stealth 

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#32]
# Decription: #
if you are stealthed nearby someone who gets chain lightning- it will hit you and remove your stealth
# How it works: #

# How it should work: #
it should not jump to stealthed targets
# Source - You need to provide a source as evidence: #
i think its commonly known
# Additional Information: #

**Comment by BlessedPinkie** [comment]
If someone can provide any sort of confirmation that it shouldn't, I can resolve it pretty easily.

**Comment by BlessedPinkie** [comment]
Chain Lightning & Multi-shot will no longer hit stealthed targets. Researching this issue it seems a bit up in the air as to when blizzard changed these spells to break stealth. The only thing I can confirm is it didn't happen in classic but it did in later expansions. Considering I can't find evidence as to a precise patch or expansion I've decided to make it so they don't break stealth.

**Comment by oldspices** [comment]
I was just in AV and multi shot broke my steatlh :(  . hunter was far away and i did not have hunters mark on me, so it should not have done that.
