### ISSUE TITLE
🐛 [Bug Report] - vengeful gladiator dragonhide gloves equip effect does not work

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#33]
# Decription: #
the gloves simply do not work~ 
# How it works: #
Equip: Causes your Maim ability to interrupt spellcasting and prevent any spell in that school from being cast for 3sec.
# How it should work: #
it should act as a mini kick, locking that school of magic
# Source - You need to provide a source as evidence: #

# Additional Information: #
aside from their very usefulness in pvp ~ I was hoping to use these for certain PVE encounters as it allows feral druids to "kick" on bosses and be more useful, but sadly it looks like these dont work.

**Comment by BlessedPinkie** [comment]
If I can replicate it should be an easy fix so expect it to be resolved shortly.

**Comment by oldspices** [comment]
just tested in duel vs desquarius and he said didnt work :/

**Comment by BlessedPinkie** [comment]
@oldspices Retest I've reworked it.

**Comment by oldspices** [comment]
works thx
