### ISSUE TITLE
🐛 [Bug Report] - arms warrior talent second wind proc

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#34]
# Decription: #
procs when stuns/roots are "immune" such as a druids roots after there is full DR- roots immune but second wind procs--- it also does not proc from many stuns such as improved concussive shot, etc. 
# How it works: #

# How it should work: #

# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by oldspices** [comment]
i should test to see if it procs on resists, too.

**Comment by BlessedPinkie** [comment]
Invalid Template - please repost. I know this may be frustrating but I can't have people get lazy and start ignoring the set template. With no fix to this post after 3 days I can only assume the poster has no intention to amend the bug report
