### ISSUE TITLE
🐛 [Bug Report] - Vial of the sunwell does not gain charges from druid hots

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#35]
# Decription: #
https://tbc-twinhead.twinstar.cz/?item=34471
# How it works: #
hots do not gain charges
# How it should work: #
should gain charges
# Source - You need to provide a source as evidence: #
use vial as druid
# Additional Information: #
its a trinket it should work

**Comment by BlessedPinkie** [comment]
Need some form of confirmation that it procc'd of instant heals, saying 'its a trinket it should work' isnt solid in terms of providing evidence that this is a bug.

**Comment by Exeasd** [comment]
[https://www.wowhead.com/item=34471/vial-of-the-sunwell&bonus=4080#comments:id=263909](url)

> Since this has been dropping so many times for my group we gave the last one to our hunter for fun. Hilariously, Mend Pet counts as a healing spell and grants the hunter the Holy Energy necessary to use the 2,000 point instant heal.

Is that enough of a evidance, or should i perhaps look for some old videos instead?

**Comment by HORSTCORE** [comment]
http://tbc.cavernoftime.com/item=34471
Well the tooltip clearly does not say "direct healing spells" or sth. like that. Cant find any videos on it tho.
