### ISSUE TITLE
🐛 [Bug Report] - Pet buffs and LoS [Bestial Wrath, Mend Pet]

### ISSUE THREAD

**Issue by Exeasd** [DramatimeWoW/TBC5ManTracker#39]
# Decription: #
When you cast the bestial wrath when you dont have LoS to your pet, the skill gets put to cooldown state even tho you didnt rly used it. Mend pet works simmiliar way, hunter is using mana to cast mend pet, even tho the cast itself is thrown in to the abyss :)
# How it works: #

# How it should work: #
If your pet is out of side you shouldnt be able to cast spells on him 
# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by BlessedPinkie** [comment]
Requires proof that these spells ignore LOS.

**Comment by Exeasd** [comment]
[https://youtu.be/LamuL4e4Y0E?t=48](url) for good 6 sec hunter is spamming bw when pets is in los and nothing happens :)

**Comment by BlessedPinkie** [comment]
Ah I see what you're saying now, it's not the LOS thats an issue it's the lack of a warning/spell not being cast.
