### ISSUE TITLE
🐛 [Bug Report] - Delay on flag pickup in WSG

### ISSUE THREAD

**Issue by Polen88** [DramatimeWoW/TBC5ManTracker#43]
# Decription: #
After dropping WSG flag there is a ~2 seocnd delay before it can be picked up again.
# How it works: #
After dropping WSG flag there is a ~2 seocnd delay before it can be picked up again. It makes it impossible for example hunter or mage to feing dead to trick enemy and pickup flag and run, or iceblock to remove all debuffs, pick flag quick and run. Enemy will just /lol at you and pickup the flag because of your 2 second pickup delay.

# How it should work: #
There should be no delay. You should be able to icebblock, remove iceblock instantly and pickup flag. It is a standard "feature" to be able to do so as mage when you carry flag in wsg.

# Source - You need to provide a source as evidence: #
Tested with 2 classes in WSG. 

# Additional Information: #

**Comment by HORSTCORE** [comment]
Provide sauce pls.
https://tbc.cavernoftime.com/spell=23333
https://tbc.cavernoftime.com/spell=23334
Pretty sure it is intended: 
https://tbc.cavernoftime.com/spell=42792
https://www.wowhead.com/spell=42792/recently-dropped-flag
> When the flag is dropped, it becomes a clickable object where it was dropped. A capturing team member can pick it up again and keep running, but the player who dropped it will not be able to personally pick it up again for 3 seconds.
https://wowwiki.fandom.com/wiki/Warsong_Gulch#Mechanics
