### ISSUE TITLE
🐛 [Bug Report] - Quest: Tablets of Baa'ri not working in Shadowmoon Valley!

### ISSUE THREAD

**Issue by Atlanticcrab18** [DramatimeWoW/TBC5ManTracker#44]
# Decription: # Quest in Shadowmoon not working properly!

# How it works: # Cant pick up the pieces, and mobs not dropping them!

# How it should work: # Supposed to be able to pick up the fragments off the ground, and be able to loot them off the mob.

# Source - You need to provide a source as evidence: #

# Additional Information: #

**Comment by TBC5ManTracker** [comment]
![image](https://user-images.githubusercontent.com/54057901/63989296-a8f35280-ca94-11e9-8437-bc8a107b6841.png)

Working just fine. The issue is likely on your end.
