### ISSUE TITLE
🐛 [Bug Report] - hunter traps are instant if caster feign deaths after placement

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#45]
# Decription: #
hunter traps are instant-
# How it works: #
placing a trap on someone, it instantly traps them. 
# How it should work: #
it should take 2-3 seconds to "arm"
# Source - You need to provide a source as evidence: #
"Patch 2.0.1 (05-Dec-2006): Freezing Traps will now cancel combat when cast. Traps can be set while in combat, but require a 2 second arming time. "" https://wowwiki.fandom.com/wiki/Freezing_Trap under patch changes sections provides evidence- 
# Additional Information: #
its undoubtedly giving hunters an OP edge in arena.

**Comment by Exeasd** [comment]
Traps arent instant, just feign death makes them instant. Still a bug, but diffrent one :)

**Comment by oldspices** [comment]
oh well then i guess not being in combat makes them instant

**Comment by oldspices** [comment]
I dont think feigning death is the focus but more likely being in combat / out of combat.
