### ISSUE TITLE
🐛 [Bug Report] - Shaman water shield not triggered by spells

### ISSUE THREAD

**Issue by oldspices** [DramatimeWoW/TBC5ManTracker#49]
# Decription: #
The shamans Water Shield is not being triggered by spells that do not do direct damage-
# How it works: #
spells with debuff effects such as cyclone, faeri fire , DOTS, ETC, are not triggering the water shields (probably many in PVE situations too) 

# How it should work: #
"The caster is surrounded by 3 globes of water, granting 51 mana per 5 sec. When a spell, melee or ranged attack hits the caster, 201 mana is restored to the caster. This expends one water globe. Only one globe will activate every few seconds. Lasts 10 min. Only one Elemental Shield can be active on the Shaman at any one time. 
This clearly states "spells" and not "direct damage spells"
# Source - You need to provide a source as evidence: #
from patch notes - "Patch 2.1.0 (22-May-2007): When a Shaman with this spell active is afflicted with Cyclone, the charge burned will now grant mana. " this is clear proof that spells that do not do direct damage should be proccing it- and they must have had an issue with cyclone making them immune and not giving the mana- tested here it does not even take a charge off shield. 
https://wowwiki.fandom.com/wiki/Water_Shield
https://wowwiki.fandom.com/wiki/Patch_2.1.0
# Additional Information: #
quite frustrating to be 100% oom as a warlock dots you up and kills you XD - you should NOT get mana from the dot ticks ~~ But the application of the spell should trigger it, at least. 
I imagine once i start pve there are other problems with it not triggering. (such as fears, etc)

**Comment by BlessedPinkie** [comment]
Mana sheild was reworked to include a lot of boss spells a little while ago, for pve it's in a good spot.

**Comment by oldspices** [comment]
ok~ Im keen to play for pvp (arena) so this is why i made report mostly. im not sure how hard this stuff is to rework but it would be cool - even to those who dont realize the help it does
