### ISSUE TITLE
🐛 [Bug Report] - Hunter steadyshot not castable in both Kaels TK/MGT

### ISSUE THREAD

**Issue by Neilltheone** [DramatimeWoW/TBC5ManTracker#51]
# Decription: # When KT throws you in the air you are not able to use Autoshot or Steadyshot. Only instant cast shots and Aimed shot.

# How it works: # Gets thrown in the air, cannot autoshot or steadyshot

# How it should work: # I should be able to cast SS and continually autoshot while in the air.

# Source - You need to provide a source as evidence: # https://youtu.be/L_-ZWdT8BOw?t=375 ( Even though it's WOTLK, the same principle is applied. ) 

# Additional Information: # Extremely gamebreaking as my rotation calls for both of these abilities in synergy. Thank you

**Comment by DramatimeWoW** [comment]
I've tested and sent a fix to Yatzii for this issue so should be resolved soon.
