### ISSUE TITLE
🐛 [Bug Report] -  Raene's Cleansing - quest - part 3

### ISSUE THREAD

**Issue by Lopiik** [DramatimeWoW/TBC5ManTracker#57]
# Decription: # 
Incorrect spawning of the chest after killing Rotting Slime.

# How it works: #  
Instead of a chest, there is complete nonsense.

# How it should work: # 
Iron Pommel should fall from the chest that appears after killing Rotting Slime.

# Source - You need to provide a source as evidence: # 
![1](https://user-images.githubusercontent.com/54949423/64355496-9ed7d380-d001-11e9-97f2-c5994c271992.png)

# Additional Information: #
wowhead with all details - https://classic.wowhead.com/quest=1027/raenes-cleansing

**Comment by BlessedPinkie** [comment]
The furbog item I assume you are aiming to get is now on the ToA vendor. Just needs a restart.

**Comment by Lopiik** [comment]
You're absolutely right :D, thanks for the solution :)
