### ISSUE TITLE
🐛 [Bug Report] - Swamplord Musel'ek in The Underbog spams Ice Trap 

### ISSUE THREAD

**Issue by DramatimeWoW** [DramatimeWoW/TBC5ManTracker#7]
# Decription: #

Swamplord Musel'ek spams his Ice Trap ability.

# How it works: #

Swamplord Musel'ek spams his Ice Trap ability.

# How it should work: #

Swamplord Musel'ek should not spam his Ice Trap ability.

# Source - You need to provide a source as evidence: #

Ya ok.

# Additional Information: #

**Comment by BlessedPinkie** [comment]
Swamplord Musel'ek got a new script faily recently, this needs re-testing.
