### ISSUE TITLE
🐛 [Bug Report] - Shadow Labs 2nd Boss MC Spell makes boss Evade

### ISSUE THREAD

**Issue by DramatimeWoW** [DramatimeWoW/TBC5ManTracker#9]
# Decription: #

The MC spell makes  the boss evade and the players do not do any action to each other.

# How it works: #

The MC spell makes  the boss evade and the players do not do any action to each other.

# How it should work: #

Players should attack one another and the boss should stand there until the MC duration is over (without evading)

# Source - You need to provide a source as evidence: #

https://youtu.be/T0JDkX-ZYjY

# Additional Information: #

**Comment by BlessedPinkie** [comment]
The spell has been removed from the fight until the work is completed to fully implement working character spells when pocessed.
